### ISSUE TITLE
Use mission execution id to get step status

### ISSUE THREAD

**Issue by eivindsjovold** [equinor/isar-exr#37]
**Describe the improvement you would like to see**
Instead of using the robotId to get step status, use the mission execution id/mission id. 
The current implementation requires a mission to be running to actually get mission status, and we have to assume the `Successful` status if no mission is running on the robot.

**How will this change existing functionality?**
More reliable step status from energy robotics api

**How will this improvement affect the current Threat Model?**
Improve by having more robust overview of robot

**Comment by eivindsjovold** [comment]
<img width="695" alt="Screenshot 2023-03-03 at 10 26 18" src="https://user-images.githubusercontent.com/66949993/222683328-e6b06283-8b9d-4778-a66a-4b0de312be14.png">
When this is implemented we can remove this poor workaround

**Comment by Afonso-2403** [comment]
No longer relevant since we query on `mission_status` instead of `step_status`, the workaround is still there as pointed out in #83
