### ISSUE TITLE
Use customer tag instead of key in points of interest

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/isar-exr#73]
**Describe the improvement you would like to see**
Currently, when upserting points of interest, we are setting the key to be the echo tag.
Energy Robotics will have a field called customer_tag(?) in Points of Interest that should be the one being set to the echo tag, and let the key be autogenerated.

**How will this change existing functionality?**
We will have to query on exiting customer tags instead of keys when upserting point of interest, besides that nothing should be affected.

**How will this improvement affect the current Threat Model?**
Leave blank for maintainers to fill out if you are uncertain about this.

**Comment by aestene** [comment]
Awaiting implementation by vendor

**Comment by Afonso-2403** [comment]
Implementation by vendor is available, closing as this will be fixed by the more comprehensive #80
