### ISSUE TITLE
Wait for CurrentSiteSnapshotHeadSelectionprocessingPipeline to finish before running mission

### ISSUE THREAD

**Issue by Christdej** [equinor/isar-exr#86]
**Describe the bug**
When we set the current site snapshot head we need to wait for the pipeline to finish before we can do anything else, or else we wont be able to run.

Need to create a waiter for CurrentSiteSnapshotHeadSelectionprocessingPipeline to complete. 
Also add a timer that will stop the execution if CurrentSiteSnapshotHeadSelectionprocessingPipeline takes to long.

**Comment by Afonso-2403** [comment]
Closed by #89
