### ISSUE TITLE
Robot pose and inspection target is now part of same Definition in GQL

### ISSUE THREAD

**Issue by Christdej** [equinor/isar-exr#87]
**Describe the improvement you would like to see**
At the moment we first create a way point for the robot to drive, then we create a inspection for the robot to inspect. In the newer versions of Energy Robotics GraphQL API the insecption can take a robot pose aswell as an inspection target, so we are creating the way point without needing to do so.

**Comment by Afonso-2403** [comment]
Closed by #88
