### ISSUE TITLE
Starting a mission on the real robot gives a 500 error

### ISSUE THREAD

**Issue by Afonso-2403** [equinor/isar-exr#92]
**Describe the bug**
When running `initiate_mission` against the real robot the query `startMissionExecution` to the API fails with a 500 error.

**To Reproduce**
Start a mission on the robot.

**Expected behavior**
This works against the simulator, so it is expected that it works also on the real robot, might need to involve Energy Robotics when testing?

**Logs**
```
graphql_client - The Energy Robotics server returned an error: [{'message': 'Request failed with status code 500', 'locations': [{'line': 2, 'column': 3}], 'path': ['startMissionExecution'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'status': 500, 'originalError': {'message': 'Request failed with status code 500', 'error': 'Internal Server Error', 'statusCode': 500}}}]
```

**Comment by oysand** [comment]
Investigate and test on wednesday

**Comment by andchiind** [comment]
Did not occur on the real robot during testing
